export const defaultOperationalSettings = {
  preferences: {
    sounds: true,
    confirmations: true,
    autoUpdates: false,
  },
  gymHours: {
    weekdaysStart: '06:00',
    weekdaysEnd: '22:00',
    saturdayStart: '07:00',
    saturdayEnd: '18:00',
  },
  finance: {
    currency: 'AOA',
    taxName: 'IVA',
    taxRate: 0,
    receiptPrefix: 'NG',
    invoiceSeries: '2026',
    receiptFooter: 'Obrigado pela preferencia.',
    paymentMethods: [
      {
        id: 'cash',
        name: 'Dinheiro',
        enabled: true,
        settlementDays: 0,
        feePercent: 0,
      },
      {
        id: 'debit',
        name: 'Cartao de debito',
        enabled: true,
        settlementDays: 1,
        feePercent: 1.5,
      },
      {
        id: 'credit',
        name: 'Cartao de credito',
        enabled: true,
        settlementDays: 2,
        feePercent: 2.5,
      },
      {
        id: 'transfer',
        name: 'Transferencia',
        enabled: true,
        settlementDays: 0,
        feePercent: 0,
      },
      {
        id: 'reference',
        name: 'PIX/Referencia',
        enabled: true,
        settlementDays: 0,
        feePercent: 0,
      },
    ],
  },
  contracts: {
    graceDays: 3,
    renewalNoticeDays: 5,
    autoRenew: true,
    allowFreeze: true,
    maxFreezeDays: 15,
    blockOnOverdue: true,
    defaultContractModel: 'Contrato padrao mensal',
  },
  checkin: {
    manual: true,
    qrCode: true,
    biometric: false,
    turnstile: false,
    allowGuestCheckin: false,
    blockExpiredPlan: true,
    dailyLimit: 1,
    toleranceMinutes: 10,
    accessStart: '05:30',
    accessEnd: '22:00',
  },
  notifications: {
    whatsapp: true,
    email: true,
    sms: false,
    dueReminderDays: 3,
    birthdayMessage: true,
    paymentReceipt: true,
    checkinAlert: false,
  },
  integrations: {
    whatsappBusiness: false,
    paymentGateway: 'Nenhum',
    googleCalendar: false,
    turnstileProvider: 'Nenhum',
    publicApi: false,
    webhookUrl: '',
  },
  printing: {
    enabled: true,
    defaultPrinterName: 'Impressora POS Recepcao',
    connectionType: 'network',
    profile: 'generic',
    paperWidth: 58,
    networkHost: '192.168.1.50',
    networkPort: 9100,
    usbDeviceName: '',
    serialPath: 'COM1',
    webPrintMode: 'browser',
    printAgentUrl: 'http://127.0.0.1:47891',
    cashDrawerEnabled: false,
    cashDrawerPin: 0,
    cashDrawerOnTimeMs: 50,
    cashDrawerOffTimeMs: 250,
    autoPrintReceipt: true,
    openDrawerOnCashPayment: true,
  },
  backup: {
    localBackup: true,
    cloudBackup: false,
    retentionDays: 90,
    autoBackupTime: '23:30',
    exportFormat: 'JSON',
    lastBackupAt: 'Hoje, 10:30',
  },
};
